/**
 * OTPy adapter — https://otpy.ir (سامانه احراز هویت پیامکی).
 *
 * Official REST API (https://api.otpy.ir, verified against the official
 * SDK @o-t-p-y/sdk + docs at otpy.ir/docs):
 *   POST /v1/otp/send   body { phone }                    → { request_id, ttl_seconds, free }
 *   POST /v1/otp/verify body { phone, code }              → { verified: boolean }
 *   GET  /v1/usage                                       → { free_used_today, free_quota_today, paid_today, daily_limit }
 * Auth: `Authorization: Bearer <API_KEY>` header. Errors: non-2xx with
 * { error: <machine_code> }.
 *
 * CAPABILITY: MANAGED — OTPy generates and verifies the code itself and has
 * NO custom-code / raw-text API. The local `code` argument is therefore
 * IGNORED on send; verification delegates to verifyManagedOtp (see the
 * capability notes in types.ts). Our core still owns rate limits, TTL
 * (clamped to the provider-stated ttl_seconds), one-time-use and audit.
 */

import {
  fetchJson,
  sanitizeErrorText,
  httpErrorCode,
  persianError,
  type SMSProviderAdapter,
  type SMSProviderConfig,
  type OtpSendResult,
  type SmsSendResult,
} from "./types";

const BASE_URL = "https://api.otpy.ir";

interface OtpyUsage {
  free_used_today?: number;
  free_quota_today?: number;
  paid_today?: number;
  daily_limit?: number | null;
}

export class OtpyProvider implements SMSProviderAdapter {
  readonly id = "otpy" as const;
  private readonly apiKey: string;

  constructor(config: SMSProviderConfig) {
    this.apiKey = config.secrets.apiKey ?? "";
  }

  private headers(): Record<string, string> {
    return {
      authorization: `Bearer ${this.apiKey}`,
      "content-type": "application/json",
    };
  }

  /** Extract the machine-readable error code from an OTPy error body. */
  private errorOf(data: unknown): string | undefined {
    if (data && typeof data === "object" && typeof (data as { error?: unknown }).error === "string") {
      return (data as { error: string }).error;
    }
    return undefined;
  }

  async sendOtp(phone: string, _code: string): Promise<OtpSendResult> {
    // Managed: the code is generated BY OTPy — our local code is ignored.
    const { ok, status, data, networkError } = await fetchJson(`${BASE_URL}/v1/otp/send`, {
      method: "POST",
      headers: this.headers(),
      body: JSON.stringify({ phone }),
      timeoutMs: 15_000,
    });
    if (!ok) {
      const code = networkError ?? this.errorOf(data) ?? httpErrorCode(status);
      return { ok: false, errorCode: code, errorMessage: persianError(networkError ? "network_error" : code) };
    }
    const body = (data ?? {}) as { request_id?: string; ttl_seconds?: number; free?: boolean };
    return {
      ok: true,
      managed: true,
      messageId: body.request_id,
      ttlSeconds: typeof body.ttl_seconds === "number" ? body.ttl_seconds : undefined,
      detail: typeof body.free === "boolean" ? (body.free ? "ارسال رایگان (سهمیه روزانه)" : "ارسال شارژی") : undefined,
    };
  }

  async verifyManagedOtp(phone: string, code: string): Promise<SmsSendResult & { verified: boolean }> {
    const { ok, status, data, networkError } = await fetchJson(`${BASE_URL}/v1/otp/verify`, {
      method: "POST",
      headers: this.headers(),
      body: JSON.stringify({ phone, code }),
      timeoutMs: 15_000,
    });
    if (!ok) {
      const errCode = networkError ?? this.errorOf(data) ?? httpErrorCode(status);
      return {
        ok: false,
        verified: false,
        errorCode: errCode,
        errorMessage: persianError(networkError ? "network_error" : errCode),
      };
    }
    const verified = Boolean((data as { verified?: unknown } | null)?.verified);
    return { ok: verified, verified };
  }

  async testConnection(): Promise<SmsSendResult> {
    const { ok, status, data, networkError } = await fetchJson(`${BASE_URL}/v1/usage`, {
      method: "GET",
      headers: this.headers(),
      timeoutMs: 15_000,
    });
    if (!ok) {
      const code = networkError ?? this.errorOf(data) ?? httpErrorCode(status);
      return { ok: false, errorCode: code, errorMessage: persianError(networkError ? "network_error" : code) };
    }
    const usage = (data ?? {}) as OtpyUsage;
    const parts: string[] = [];
    if (typeof usage.free_used_today === "number" && typeof usage.free_quota_today === "number") {
      parts.push(`سهمیه رایگان امروز: ${usage.free_used_today}/${usage.free_quota_today}`);
    }
    if (typeof usage.paid_today === "number") {
      parts.push(`ارسال شارژی امروز: ${usage.paid_today}`);
    }
    if (typeof usage.daily_limit === "number") {
      parts.push(`سقف روزانه: ${usage.daily_limit}`);
    }
    return {
      ok: true,
      detail: parts.length ? parts.join(" — ") : "اتصال موفق بود.",
    };
  }

  // No raw-text SMS API exists on OTPy (managed OTP-only service).
  // sendSms intentionally NOT implemented — callers feature-check it.
}

/** OTPy-specific Persian labels for well-known provider error codes. */
export const OTPY_ERROR_LABELS: Record<string, string> = {
  bad_phone: "شماره موبایل برای OTPy معتبر نیست.",
  missing_api_key: "کلید API سرویس OTPy تنظیم نشده است.",
  quota_exceeded: "سهمیه روزانه سرویس OTPy به پایان رسیده است.",
};
